### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by CyberAP** [csstools/postcss-browser-comments#3]
From https://github.com/csstools/postcss-normalize/issues/42.
postcss-browser-comments is causing serious performance degradation to builds with multiple CSS files.

Profiles attached:

[profiles.zip](https://github.com/csstools/postcss-normalize/files/3383767/profiles.zip)

The slow one is with postcss-normalize enabled (that has postcss-browser-comments) and the fast one is without.

**Comment by jonathantneal** [comment]
As I mentioned in the other issue, it’s excellent of you to report this. I don’t know to read these profile JSON files. However, I’m determined to help us find a way to improve the performance here.

Would these profiles help me see more closely where the slow down occurs?

**Comment by CyberAP** [comment]
https://github.com/csstools/postcss-normalize/issues/42#issuecomment-511014684

**Comment by jonathantneal** [comment]
@CyberAP, would you mind sharing how you were able to test performance like this? I would like to add these tests into all of my plugins.

**Comment by CyberAP** [comment]
> @CyberAP, would you mind sharing how you were able to test performance like this? I would like to add these tests into all of my plugins.

Sure, I followed this guide, it provides several ways to profile webpack: https://samsaccone.com/posts/why-is-my-webpack-build-slow.html
