### ISSUE TITLE
Upgrade to PostCSS 8

### ISSUE THREAD

**Issue by devpeerapong** [csstools/postcss-browser-comments#5]
### Problem

`create-react-app` cannot upgrade to `postcss@8` https://github.com/facebook/create-react-app/issues/9664

### Solution

Upgrade PostCSS to v8

As state in [PostCSS 8.0 is coming: Here’s what it brings](https://evilmartians.com/chronicles/postcss-8-is-coming-here-is-what-it-brings)

> The new release will try to avoid breaking changes for most users. Plugins created for PostCSS 7.0 will work for PostCSS 8.0 as well.

So I think it should be easy to upgrade to v8

**Comment by msalahz** [comment]
Any updates?

**Comment by jonathantneal** [comment]
Fulfilled in https://github.com/csstools/postcss-browser-comments/commit/701fc713c7c5ac2ec72d2b33e308ae081dbb4b28
